WGApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^chess/', include('chess.urls', namespace='chess')),
    url(r'^auth/', include('loginsys.urls', namespace='loginsys')),

]

chess/urls.py
# __author__ = 'aliaksandr'

from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^competition/$', views.addCompetition, name='addCompetition'),
    url(r'^competition/(?P<pk>[0-9]+)/$', views.registerPlayers, name='registerPlayers'),
    url(r'^competition/(?P<pk>[0-9]+)/start/', views.startCompetition, name='startCompetition'),
    url(r'^competition/(?P<pk>[0-9]+)/rounds/', views.allRounds, name='allRounds'),
    url(r'^competition/(?P<comp_id>\d)/round/(?P<pk>[0-9]+)/$', views.round, name='round'),
    #url(r'^competition/(?P<competition_id>[0-9]+)/round/(?P<pk>[0-9]+)/$', views.round, name='round'),
]

loginsys/urls.py
from django.conf.urls import patterns, url, include
from . import views

urlpatterns = [
                url(r'^login/', views.login, name='login'),
                url(r'^logout/', views.logout, name='logout'),
              ]

templates/main.html
{% load staticfiles %}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.6/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.6/css/bootstrap.min.css' %}">
{#    <link rel="stylesheet" href="{% static 'chess/css/styles.css' %}">#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
    <script src="{% static 'bootstrap-3.3.6/js/bootstrap.js' %}"></script>
    <title>Шахматы</title>
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'chess:index' %}">Home</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
{#                <ul class="nav navbar-nav">#}
{#                    <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>#}
{#                  </ul>#}
                <ul class="nav navbar-nav navbar-right">
                    {% if username %}
                        <li class="active"><a href={% url 'loginsys:logout' %}>Выйти({{ username }})<span class="sr-only">(current)</span></a></li>
                    {% else %}
                        <li class="active"><a href={% url 'loginsys:login' %}>Войти<span class="sr-only">(current)</span></a></li>
                    {% endif %}
                </ul>
                </div>
        </div>

    </nav>

    <div class="container-fluid">

        {% block content %}{% endblock %}
        {% block login %}{% endblock %}

    </div>
    

</body>
</html>