WGApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^chess/', include('chess.urls', namespace='chess')),
    url(r'^auth/', include('loginsys.urls', namespace='loginsys')),

]

chess/urls.py
# __author__ = 'aliaksandr'

from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^competition/$', views.addCompetition, name='addCompetition'),
    url(r'^competition/(?P<pk>[0-9]+)/$', views.registerPlayers, name='registerPlayers'),
    url(r'^competition/(?P<pk>[0-9]+)/start/', views.startCompetition, name='startCompetition'),
    url(r'^competition/(?P<pk>[0-9]+)/rounds/', views.allRounds, name='allRounds'),
    url(r'^competition/(?P<comp_id>\d)/round/(?P<pk>[0-9]+)/$', views.round, name='round'),
    #url(r'^competition/(?P<competition_id>[0-9]+)/round/(?P<pk>[0-9]+)/$', views.round, name='round'),
]

chess/models.py
from django.db import models
# import datetime.date
from django.utils import timezone
# Create your models here.


class Competition(models.Model):
    information = models.CharField('Информация', max_length=100, blank=True)
    date = models.DateField('Дата')
    # time = models.CharField('Время', max_length=20)

    class Meta:
        db_table = 'competition'

    def __str__(self):
        return str(self.id)


class Round(models.Model):
    competition = models.ForeignKey(Competition, null=True)
    num_round = models.PositiveIntegerField()

    class Meta:
        db_table = 'round'


class Table(models.Model):
    num_competition = models.ForeignKey(Competition, null=True)
    num_table = models.PositiveIntegerField()

    class Meta:
        db_table = 'table'


class Player(models.Model):
    competition = models.ForeignKey(Competition, null=True)
    name = models.CharField('Имя игрока',max_length=100)
    age = models.PositiveIntegerField('Возраст')
    curr_ello_rate = models.PositiveIntegerField('Ello рэйтинг', help_text='Текущий рейтинг')
    new_ello_rate = models.PositiveIntegerField(blank=True, null=True)

    class Meta:
        db_table = 'player'


class Results(models.Model):
    RESULTS = (
        (1, 'Победа'),
        (0.5, 'Ничья'),
        (0, 'Проигрыш'),
    )
    player = models.ForeignKey(Player)
    competition = models.ForeignKey(Competition)
    num_round = models.PositiveIntegerField(null=True)
    num_table = models.PositiveIntegerField(null=True)
    result = models.FloatField(choices=RESULTS, null=True, blank=True)

    class Meta:
        db_table = 'results'

chess/forms.py
# __author__ = 'aliaksandr'

from django import forms
from django.forms.widgets import Widget
from chess.models import Competition, Player, Results
from django.forms.models import BaseModelForm


class CompetitionForm(forms.ModelForm):
    class Meta:
        model = Competition
        fields = ['date', 'information']
        # localized_fields = ('date', 'time')
        # widgets = {
        #     'time': (forms.TimeInput(format='%H:%M')),
        # }
        # help_texts = {
        #     'time': ('00:00'),
        # }

class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        exclude = ['new_ello_rate', 'num_table', 'num_round', 'competition']
        widgets = {
            'name': forms.Textarea(attrs={'cols': 30, 'rows': 1})
        }

class AddPlacesForms(forms.Form):
    # max_amount = Player.objects.all().count()
    places = forms.IntegerField(label="Введите количество призовых мест")

chess/views.py
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponseRedirect
from . import models, calculations
from .forms import *
import math
from django.forms.models import modelformset_factory
from django.contrib import auth
# Create your views here.


def index(request):
    return render_to_response('chess/index.html', {'username': auth.get_user(request).username})


# Создание соревнования
def addCompetition(request):
    if request.method == 'POST':
        form = CompetitionForm(request.POST)

        if form.is_valid():
            # time = form.cleaned_data['delivery_time']
            comp = form.save(commit=False)
            comp.save()
            return HttpResponseRedirect('/chess/competition/')

    else:
        form = CompetitionForm()

    competitions = models.Competition.objects.raw('SELECT * FROM competition')
    competition_count = models.Competition.objects.count()
    return render(request, 'chess/addCompetition.html', {'competitions': competitions, 'comp_count': competition_count,
                                                         'form': form, 'username': auth.get_user(request).username })


# Регистрация игроков
def registerPlayers(request, pk):
    name = None
    round_count = models.Round.objects.filter(competition_id=int(pk)).count()
    if request.method == 'POST':
        form = PlayerForm(request.POST)

        if form.is_valid():
            player = form.save(commit=False)
            player.competition_id = int(pk)
            name = player.name
            playerObject = Player.objects.filter(name=name)

            if len(playerObject) > 0:
                name = 0
            else:
                player.save()

    else:
        form = PlayerForm()

    # competitions = models.Competition.objects.raw('SELECT * FROM competition')
    return render(request, 'chess/registerPlayers.html', {'form': form, 'name': name, 'num_comp': int(pk), 'round_count': round_count,
                                                          'username': auth.get_user(request).username})


# Добавление столов и раундов
def startCompetition(request, pk):
    players = models.Player.objects.raw('SELECT id, name, curr_ello_rate FROM player WHERE competition_id={0} '
                                        'ORDER BY name ASC '.format(int(pk)))
    players_count = models.Player.objects.filter(competition_id=pk).count()
    round_count = models.Round.objects.filter(competition_id=pk).count()

    if round_count == 0:

        if request.method == 'POST':
            form = AddPlacesForms(request.POST)

            if form.is_valid():
                amount_place = form.cleaned_data['places']
                round_count = math.trunc(math.log2(players_count) + math.log2(amount_place))
                call = calculations.Query()

                for i in range(1, round_count+1):
                    call.makeQuery('INSERT INTO round VALUES (NULL, %s, %s)', [i, int(pk)])

                for i in range(1, players_count//2+1):
                    call.makeQuery('INSERT INTO table VALUES (NULL, %s, %s)', [i, int(pk)])
                # return render(request, 'chess/startCompetition.html', {'players': players, 'form': form, 'rounds': amount_round})

        else:
            form = AddPlacesForms()
        return render(request, 'chess/startCompetition.html', {'players': players, 'form': form, 'rounds': round_count,
                                                               'num_comp': int(pk), 'players_count': players_count,
                                                               'username': auth.get_user(request).username})

    return render(request, 'chess/startCompetition.html', {'players': players, 'rounds': round_count, 'num_comp': int(pk),
                                                           'players_count': players_count})


def allRounds(request, pk):
    rounds = models.Round.objects.filter(competition_id=int(pk))
    return render_to_response('chess/allRounds.html', {'rounds': rounds, 'comp_id': pk})


def round(request, comp_id, pk):
    players_count = models.Player.objects.filter(competition_id=comp_id).count()
    tables_count = players_count//2
    pair = calculations.PairCalculation(players_count, tables_count, int(pk), int(comp_id))
    query = calculations.Query()

    if int(pk) == 1:
        pair.makePairsForFirstRound()
    else:
        pair.makePairsForNextRound()
    # pair.addResults()

    resultNull_count = query.returnQuery('SELECT COUNT(id) FROM results WHERE result IS NULL ')[0][0]

    players_for_round_query = query.returnQuery('SELECT player.id, player.name, results.num_table, results.result FROM player LEFT '
                                               'JOIN results ON player.id=results.player_id WHERE results.competition_id=%s', [int(pk)])

    for i in players_for_round_query:
        print(i)

    players_for_round = {field[0]: {'name': [], 'result': []} for field in players_for_round_query}


    pair = []
    result = []

    for i in players_for_round:
        for j in players_for_round_query:
            if i == j[0]:
                pair.append(j[1])
                result.append(j[2])
                if len(pair) == 2:
                    players_for_round[i]['name'] = pair
                    players_for_round[i]['result'] = result
                    pair = []
                    result = []
    """
    data = {
        'form-TOTAL_FORMS': '1',
        'form-INITIAL_FORMS': '0',
        'form-MAX_NUM_FORMS': '',
    }
    """

    if resultNull_count > 0:
        # ResultFormSet = modelformset_factory(queryset=models.Results.objects.filter(id=2))
        ResultFormSet = modelformset_factory(models.Results, fields=('result',), max_num=players_count)
        if request.method == 'POST':
            formset = ResultFormSet(request.POST, request.FILES, queryset=models.Results.objects.filter(competition_id=comp_id, num_round=pk))
            if formset.is_valid():
                instances = formset.save(commit=False)
                for i in instances:
                    print(i.player_id)
                    i.save()


        else:
            formset = ResultFormSet(queryset=models.Results.objects.filter(competition_id=comp_id, num_round=pk))

        return render(request, 'chess/round.html', {'num_round': int(pk), 'players': players_for_round, 'resultNull': resultNull_count,
                                                'num_comp': comp_id, 'formset': formset})

    return render(request, 'chess/round.html', {'num_round': int(pk), 'players': players_for_round, 'resultNull': resultNull_count,
                                                'num_comp': comp_id})

chess/templates/chess/addCompetition.html
{% extends 'main.html' %}

{% block content %}
    <div class="col-md-offset-1">

    {% if username %}
        <div class="row">

            <h2>Добавте соревнования</h2>

            <form class="form-horizontal" action="{% url 'chess:addCompetition' %}" method="post">{% csrf_token %}
                {{ form.non_field_errors }}
{#                {{ form.errors }}#}
                <div class="form-group">
                    <label for="{{ form.date.id_for_label }}" class="col-sm-2 control-label">{{ form.date.label }}</label>
                    <div class="col-sm-4">
                        <input type="date" class="form-control" id="{{ form.date.id_for_label }}" name="date" required>
{#                        <input type="date" class="form-control" id="{{ form.date.id_for_label }}" name="date" required value="{{ form.date.value }}">#}
{#                        {{ form.date }}#}
                    </div>
                </div>

{#                <div class="form-group">#}
{#                    {{ form.time.errors }}#}
{#                    <label for="{{ form.time.id_for_label }}" class="col-sm-2 control-label">{{ form.time.label }}</label>#}
{#                    <div class="col-sm-4">#}
{#                        {{ form.time }}#}
{#                        <input type="text" id="{{ form.time.id_for_label }}" class="form-control" name=time" placeholder="{{ form.time.help_text }}"#}
{#                               required>#}
{#                    </div>#}

{#                </div>#}
                <div class="form-group">
                    <label for="{{ form.information.id_for_label}}" class="col-sm-2 control-label">{{ form.information.label }}</label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" id="{{ form.information.id_for_label }}" name="information"
                               placeholder="Дополнительная информация">
                    </div>
                </div>

                <div class="form-group">
                    <label></label>
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </div>
                </div>

            </form>

        </div>
    {% endif %}

        <div class="col-md-offset-2 col-md-7">
            <table class="table">
                <caption><h4>Доступные соревнования {{ comp_count }}</h4></caption>
                <tr>
                    <th>Номер соревнования</th>
                    <th>Дата проведения</th>
                    <th>Время проведения</th>
                    <th>Информация</th>
                </tr>

                {% for competition in competitions %}

                    <tr>
                        {% if username %}
                            <th><a href="{% url 'chess:registerPlayers' competition.id %}">{{ competition.id }}</a></th>
                        {% else %}
                            <th><a href="{% url 'chess:startCompetition' competition.id %}">{{ competition.id }}</a></th>
                        {% endif %}

                        <th>{{ competition.date }}</th>
                        <th>{{ competition.time }}</th>
                        <th>{{ competition.information }}</th>

                    </tr>

                {% endfor %}
            </table>
        </div>

    </div>
{% endblock %}

chess/templates/chess/allRounds.html
{% extends 'main.html' %}

{% block content %}

    <div class="col-md-offset-2 col-md-6">
        <div class="list-group">
            {% for round in rounds %}
                <a href="{% url 'chess:round' comp_id=comp_id pk=round.num_round %}"
                   class="list-group-item" title="Просмотреть">{{ round.num_round }} раунд</a>
            {% endfor %}

        </div>
    </div>
{% endblock %}

chess/templates/chess/index.html
{% extends 'main.html' %}

{% block content %}

    <div class="col-md-offset-1">
        {% if username %}
            <h2 ><a href="{% url 'chess:addCompetition' %}">Начать соревнование</a></h2>
        {% else %}
            <button type="button" class="btn btn-link btn-lg"><a href="{% url 'chess:addCompetition' %}">Список доступных соревнований</a></button>
        {% endif %}
    </div>

    <div class="col-md-offset-1 col-md-10 jumbotron">

        <p class="text">Швейцарская система — система проведения спортивных турниров. Особенно распространена в интеллектуальных играх,
            таких как шахматы, шашки, сёги, го, рэндзю и им подобных. Впервые была применена на шахматном турнире в Цюрихе
            (Швейцария) в 1895 году, откуда и получила своё название. Характерна тем, что турнир проходит без выбывания и
            позволяет для определения победителей обойтись небольшим числом туров при большом числе участников.</p>

        <p><strong class="super">Порядок проведения турнира.</strong></p>
        <p class="rules">
            В первом туре все игроки упорядочиваются (случайным жребием, или по рейтингу). Пары составляются по принципу:
            первый из верхней половины таблицы с первым из нижней половины, второй – со вторым, и так далее.
            Если, например, в турнире 40 участников, то первый играет с 21-м, второй с 22-м и т. д.
            При нечётном числе игроков игрок, имеющий последний номер, получает очко без игры.</p>
        <p class="rules">
            В следующих турах все игроки разбиваются на группы с одинаковым количеством набранных очков.
            Так, после первого тура групп будет три: выигравшие, проигравшие и сыгравшие вничью.
            Если в группе оказывается нечётное количество игроков, то один игрок переводится в следующую очковую группу.</p>
        <p class="rules">
            Пары игроков для следующего тура составляются из одной очковой группы по тому же, что и в первом туре, рейтинговому
            принципу (лучший игрок из верхней половины группы по возможности встречается с лучшим игроком из нижней половины
            этой группы). При этом, однако, не допускается, чтобы одна и та же пара играла в турнире более одной игры.
            При игре в шахматы или шашки, кроме того, действует правило чередования цвета: желательно, чтобы у каждого
            участника от тура к туру чередовался цвет фигур (чтобы игрок имел равное количество игр белыми и чёрными),
            в любом случае не допускается три партии подряд (в шашках — четыре) одним цветом, кроме последнего тура.
            При нечётном числе игроков игрок, имеющий последний номер в последней очковой группе (из ещё не получавших очко
            за пропуск), получает очко без игры.</p>
        <p class="rules">
            Места в турнире распределяются по набранному количеству очков.</p>
        <p class="rules">
            Участники, набравшие равное количество очков, обычно распределяются по коэффициенту Бухгольца, который определяется
            как сумма очков, набранных всеми соперниками данного игрока в турнире. Кроме него (или вместе с ним) может
            применяться средний рейтинг соперников (тому, у кого соперники имеют более высокий средний рейтинг, присуждается
            более высокое итоговое место) или так называемый «коэффициент прогресса» — более высокое место получает игрок,
            который по ходу турнира дольше находился на более высоком месте, чем набравший равное число очков соперник).</p>
    </div>
    <script>$("p").dblclick(function () {
        $("#div1").fadeIn();
            });
    </script>
{% endblock %}

chess/templates/chess/registerPlayers.html
{% extends 'main.html' %}

{% block content %}

    {% if round_count %}
        <div class="alert alert-warning">
            <strong>Регистрация игроков завершена!</strong>
        </div>
        <h2><a href="{% url 'chess:startCompetition' num_comp %}" >Перейти к соревнованию</a></h2>
    {% else %}

        <div class="col-md-offset-1 col-md-7">
            {% if name %}
                <div class="alert alert-success">Игрок <strong>{{ name }}</strong> зарегистрирован</div>
            {% elif name == 0 %}
                <div class="alert alert-warning" role="alert">Игрок уже зарегистрирован</div>
            {% endif %}

            <h2><a href="{% url 'chess:startCompetition' num_comp %}" >Завершить регистрацию</a></h2>

            <form action="{% url 'chess:registerPlayers' num_comp %}" method="post">{% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    <div class="fieldWrapper">
                        {{ form.name.errors }}
                        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                        <input type="text" class="form-control" id="{{ form.name.id_for_label }}" placeholder="{{ form.name.label }}" name="name">
                    </div>
                </div>

                <div class="form-group">
                    <div class="fieldWrapper">
                        {{ form.age.errors }}
                        <label for="{{ form.age.id_for_label }}">{{ form.age.label }}</label>
                        <input type="number" class="form-control" id="{{ form.age.id_for_label }}" placeholder="{{ form.age.label }}" name="age">
                    </div>
                </div>
                <div class="form-group">
                    <div class="fieldWrapper">
                        {{ form.curr_ello_rate.errors }}
                        <label for="{{ form.curr_ello_rate.id_for_label }}">{{ form.curr_ello_rate.label }}</label>
                        <input type="number" class="form-control" id="{{ form.curr_ello_rate.id_for_label }}"
                               placeholder="{{ form.curr_ello_rate.help_text }}" name="curr_ello_rate">
                    </div>
                </div>
                <br>
                <input class="btn btn-success btn-lg" type="submit" value="Зарегистрировать игрока">
            </form>
        </div>
    {% endif %}

{% endblock %}

chess/templates/chess/round.html
{% extends 'main.html' %}

{% block content %}

    <div class="row">
        <div class="col-md-offset-2">
            <h2>Номер раунда {{ num_round }}</h2>

            {% if resultNull == 0 %}
                <h2><a href={% url 'chess:round' comp_id=num_comp pk=2 %}>Начать следующий раунд</a></h2>
            {% endif %}
        </div>
    </div>


    <div class="row">
        <div class="col-md-5 col-md-offset-1">

            <br>

                <table class="table" border="2">

                    <tr>
                        <th>Пара игроков</th>
                        <th>Результаты</th>
                    </tr>

                    {% for key in players %}
                        {% for player in players.items %}
                            {% if key == player.0 %}

                                <tr>
                                   <td>{{ player.1.name.0 }} - {{ player.1.name.1 }}</td>

                                    {% if player.1.result.0 %}
                                        <td>{{ player.1.result.0 }} : {{ player.1.result.1 }}</td>

                                    {% else %}
                                        <td>{{ player.1.result.0 }} : {{ player.1.result.1 }}</td>
                                    {% endif %}

                                </tr>

                            {% endif %}
                        {% endfor %}
                    {% endfor %}

                </table>

        </div>
    </div>
    {% if resultNull > 0 %}

        <form action="{% url 'chess:round' comp_id=num_comp pk=num_round %}" method="post">{% csrf_token %}
            {{ formset.management_form }}
            {% for form in formset %}
                {% for field in form %}

                    {{ field }}
                {% endfor %}

            {% endfor %}


            <input type="submit" value="Push">

        </form>

    {% endif %}
    <div class=""></div>

{% endblock %}

chess/templates/chess/startCompetition.html
{% extends 'main.html' %}

{% block content %}

    {% if username %}

        <div class="col-md-offset-1">
            {% if rounds %}

                <h4>Необходимое количество раундов: {{ rounds }}</h4>
                <h4><a href="{% url 'chess:round' comp_id=num_comp pk=1 %}">Начать соревнование</a></h4>

                {% else %}

                    <form class="form-inline" action="{% url 'chess:startCompetition' num_comp %}" method="post">{% csrf_token %}
                        <div class="form-group">

                            {{ form.places.errors }}
{#                            {{ form.places.label_tag }}#}
{#                            <input type="number" name="places" id="{{ form.places.id_for_places }}" required min="1" max="{{ players_count }}">#}
                            <label class="sr-only" for="{{ form.places.id_for_places }}">{{ form.places.label }}</label>
                            <div class="input-group">
                                <input type="number" name="places" id="{{ form.places.id_for_places }}" required min="1" max="{{ players_count }}"
                                    placeholder="{{ form.places.label }}" style="width: 20em">
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </form>
            {% endif %}
        </div>
        <br>
    {% endif %}

        <div class="col-md-offset-1 col-md-5">

            <h4><a href="{% url 'chess:allRounds' num_comp %}">Количество раундов: {{ rounds }}</a></h4>

            <table class="table table-hover">
                <caption><h4>Зарегистрированно игроков: {{ players_count }}</h4></caption>
                <tr>
                    <th>Номер игрока</th>
                    <th>Имя игрока</th>
                    <th>Возраст</th>
                    <th>Текущий Ello рэйтинг</th>
                </tr>
                {% for player in players %}
                    <tr class="active">
                        <th>{{ player.id }}</th>
                        <th>{{ player.name }}</th>
                        <th>{{ player.age }}</th>
                        <th>{{ player.curr_ello_rate }}</th>
                    </tr>
                {% endfor %}
            </table>
        </div>


{% endblock %}